language: generic
sudo: required

services:
    - docker
    
before_install:
    - docker build -t ricob1980/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true ricob1980/docker-react npm run test